println("dit is een tekst");
println("Dit is een tekst.");
print("Dit is een");
print(" stukje tekst");
println(" achter elkaar geplakt!");
print("Met 2 enters.");
print("elllo"); 
print("hoe gaat");
println("oke hallo");
print("oke");
